select lpad( format( count(distinct core_mailing.id), 0 ), 12, ' ' ) as "mailing_count",
       lpad( format( sum( ( select count(*) from core_usermailing where core_usermailing.mailing_id = core_mailing.id ) ), 0 ), 12, ' ' ) as "sent_count",
       lpad( concat( format( 100 * sum( ( select count( distinct user_id ) from core_open where core_open.mailing_id = core_mailing.id  ) ) / sum( ( select count(*) from core_usermailing where core_usermailing.mailing_id = core_mailing.id ) ), 1 ), '%' ), 8, ' ' ) as "open_rate",
       lpad( format( sum( ( select count( distinct user_id ) from core_click join core_clickurl on ( core_click.clickurl_id = core_clickurl.id ) where core_click.mailing_id = core_mailing.id and not core_clickurl.url like '%/unsubscribe/%'  ) ), 0 ), 12, ' ' ) as "clicks",
       lpad( concat( format( 100 * sum( ( select count( distinct user_id ) from core_click join core_clickurl on ( core_click.clickurl_id = core_clickurl.id ) where core_click.mailing_id = core_mailing.id and not core_clickurl.url like '%/unsubscribe/%'  ) ) / sum( ( select count(*) from core_usermailing where core_usermailing.mailing_id = core_mailing.id ) ), 1 ), '%' ), 8, ' ' ) as "click_rate",
       lpad( concat( format( 100 * sum( ( select count( distinct user_id ) from core_action left join core_unsubscribeaction on ( core_unsubscribeaction.action_ptr_id = core_action.id ) where core_action.mailing_id = core_mailing.id and core_action.status = 'complete' and core_unsubscribeaction.action_ptr_id is null  ) ) / sum( ( select count(*) from core_usermailing where core_usermailing.mailing_id = core_mailing.id ) ), 1 ), '%' ), 8, ' ' ) as "action_rate",
       lpad( concat( format( 100 * sum( ( select count( distinct core_action.user_id ) from core_unsubscribeaction join core_action on (core_unsubscribeaction.action_ptr_id=core_action.id) join core_subscriptionhistory on (core_action.id = core_subscriptionhistory.action_id) where core_action.mailing_id = core_mailing.id  ) ) / sum( ( select count(*) from core_usermailing where core_usermailing.mailing_id = core_mailing.id ) ), 1 ), '%' ), 8, ' ' ) as "unsub_rate"
from core_mailing
where exists ( select * from core_mailing_tags where core_mailing_tags.mailing_id = core_mailing.id and core_mailing_tags.tag_id in ( {{ Tag_ids_for_Tags }} ) )
  and core_mailing.status = 'completed'
  and not ( notes like concat( '%', 'staff', '%' ) )